default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ci_rails_development
  username: ci_rails
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: ci_rails_test
  username: ci_rails
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: ci_rails_production
  username: ci_rails
  password: <%= ENV['CI_RAILS_DATABASE_PASSWORD'] %>
